site_name: Floowandereeze & Modding - Duel Links
repo_url: https://github.com/nauder/floowandereeze-and-modding-dl
theme:
  name: material
  favicon: assets/icon.png
  logo: assets/ico.png
  features:
    - navigation.footer

  palette:

    - scheme: default
      primary: blue
      accent: dark blue
      font:
        text: white
        link: light blue
        code: light blue
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    - scheme: slate
      primary: blue
      accent: dark blue
      font:
        text: white
        link: light blue
        code: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    
nav:
  - Home: index.md
  - Features:
    - Configuration: features/config.md
    - Card Editor: features/card.md
    - Card Sleeve Editor: features/sleeve.md
    - Playmat Editor: features/field.md
  
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nauder/floowandereeze-and-modding-qt
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/nauder